image: node:10.15.1

stages:
    - build
    - test
    
build:
    stage: build
    services:
        - mongo:latest
    script:
      - npm install npm@latest -g
      - npm install
      - node ./src/index.js

test:
    stage: test
    script:
        - npm run test
